services:
  - type: web
    name: library-management-system
    runtime: java
    plan: free
    buildCommand: "chmod +x mvnw && ./mvnw clean package -DskipTests"
    startCommand: "java -jar target/library-management-system-1.0.0.jar"
    healthCheckPath: /
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: FINE_PER_DAY
        value: "20"
      - key: JAVA_VERSION
        value: "21"
