-- ═══════════════════════════════════════════════════════════
--  Library Management System – MySQL Database Setup Script
-- ═══════════════════════════════════════════════════════════
--  Run this script ONCE before starting the application.
--  It creates the database. Tables are auto-generated by Hibernate.
-- ═══════════════════════════════════════════════════════════

CREATE DATABASE IF NOT EXISTS library_db
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE library_db;

-- Hibernate will auto-create tables via spring.jpa.hibernate.ddl-auto=update.
-- The tables it generates are:
--   1. users            (id, username, password, email, full_name, enabled)
--   2. roles            (id, name)
--   3. user_roles       (user_id, role_id)   — join table for @ManyToMany
--   4. categories       (id, name, description)
--   5. books            (id, title, author, isbn, total_copies, available_copies,
--                         description, published_year, category_id)
--   6. borrow_records   (id, user_id, book_id, borrow_date, due_date,
--                         return_date, status)
--
-- Default data (roles, admin user, categories) is seeded by DataInitializer.java
-- on first run.
